# Generated by Django 5.1.1 on 2024-10-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='broker',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='broker',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='PIN',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
